packages:
  - 'applications/*'
  - 'shared-packages/*'
  - 'background-services/*'

catalog:
  react: ^18.2.0
  typescript: ^5.2.0
  vite: ^5.0.0
  tailwindcss: ^3.3.0
  @types/node: ^20.10.0
  @types/react: ^18.2.0
  @types/react-dom: ^18.2.0
  express: ^4.18.0
  prisma: ^5.7.0
  '@prisma/client': ^5.7.0
